PR-Trigger/index.js, src/_tests/fixtures/43314/result.json
Updates some logs and adds an allsowlist of events which can trigger the run
=> Allow only a certain set of PR actions to trigger the run

host.json
I've set the `WEBSITE_MAX_DYNAMIC_APPLICATION_SCALE_OUT` in the config, and this is the second part - I copied the values from the docs https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#singleton
Fixes #3
=> Adds a host setting to make the function act as a singleton

src/execute-pr-actions.ts
Should make it easier for us to see the differences in issues
=> Don't needlessly edit posts to the same content

PR-Trigger/index.js
This adds the code support for https://github.com/DefinitelyTyped/dt-mergebot/issues/2 - it doesn't include support for `status` because I'm still thinking about that, but at least reviews and comments will work now 👍
=> Support multiple sources of webhooks

PR-Trigger/index.js
Validates that the webhook has come from GitHub
=> Validate the webhooks from github

PR-Trigger/index.js, src/_tests/fixturedActions.test.ts, src/_tests/fixtures/43695/result.json, src/_tests/fixtures/44105/_response.json, src/_tests/fixtures/44105/owners.json, src/_tests/fixtures/44105/result.json, src/_tests/fixtures/44290/_response.json, src/_tests/fixtures/44290/derived.json, src/_tests/fixtures/44290/owners.json, src/_tests/fixtures/44290/result.json, src/commands/create-fixture.ts, src/commands/process-single.ts, src/commands/show-info.ts, src/pr-info.ts, src/pr-query.ts, src/schema/PR.ts
=> Adds support for not running on closed/merged/draft PRs

PR-Trigger/index.js, src/_tests/fixtures/44288/_response.json, src/_tests/fixtures/44288/derived.json, src/_tests/fixtures/44288/owners.json, src/_tests/fixtures/44288/result.json, src/pr-info.ts
=> Lets tsx files get picked up as tests

PR-Trigger/index.js, README.md, src/_tests/labels.test.ts
Now it's in prod this code / docs is dead weight
=> Remove the start/end range feature

src/_tests/fixtures/43960-post-close/mutations.json, src/_tests/fixtures/44105/mutations.json, src/_tests/fixtures/44290/mutations.json, src/commands/process-single.ts, src/execute-pr-actions.ts
TODO: check query/mutation responses for errors
=> Fix remove card mutation

src/_tests/fixtures/43144/mutations.json, src/_tests/fixtures/43144/result.json, src/comments.ts
This message felt like it was missing a congrats! https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44392#issuecomment-622121057
=> Improve merge message

PR-Trigger/index.js
=> Don’t process anything when the webhook is triggered by typescript-bot

src/_tests/fixtures/44402/_response.json, src/_tests/fixtures/44402/derived.json, src/_tests/fixtures/44402/mutations.json, src/_tests/fixtures/44402/result.json, src/compute-pr-actions.ts, src/pr-info.ts
If we get a PR where no packages are changed:
- don't say anything
- move to "Needs Maintainer Review" so it ends up on our TODO
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44402 as an example PR
Fixes #46
=> NOOP for PRs which don't affect packaages

src/pr-info.ts
=> Switch to prefix searching for 'ready to merge' 

src/compute-pr-actions.ts
=> Fix removing the PR from a project board

README.md, src/pr-info.ts, src/queries/pr-query.ts, src/queries/schema/GetPRForStatus.ts, src/queries/schema/PR.ts
=> Use switching from draft as a last date too

DailyOpenPRCheck/function.json, DailyOpenPRCheck/index.js, DailyOpenPRCheck/readme.md, src/queries/all-open-prs-query.ts, src/queries/schema/GetAllOpenPRs.ts, src/queries/schema/GetPRForStatus.ts
This should handle us not handling idle states
=> Adds a scheduled task which runs the bot all open PRs

docs/how-it-works.md, src/comments.ts, src/pr-info.ts
Start of some user-land docs I had laying around
=> Adds some docs and changes wording a bit

docs/how-it-works.md, src/comments.ts, src/compute-pr-actions.ts
=> Week -> Month for timeout

src/_tests/fixtures/43314/mutations.json, src/_tests/fixtures/43314/result.json, src/_tests/fixtures/44299/mutations.json, src/_tests/fixtures/44299/result.json, src/compute-pr-actions.ts
=> New libs should always end up in DT maintainer review

src/_tests/fixtures/43136/mutations.json, src/_tests/fixtures/43136/result.json, src/_tests/fixtures/43175/mutations.json, src/_tests/fixtures/43175/result.json, src/_tests/fixtures/44267/mutations.json, src/_tests/fixtures/44267/result.json, src/_tests/fixtures/44316/mutations.json, src/_tests/fixtures/44316/result.json, src/_tests/fixtures/44411/mutations.json, src/_tests/fixtures/44411/result.json, src/_tests/fixtures/44424-1-travis-instantly-finished/mutations.json, src/_tests/fixtures/44424-1-travis-instantly-finished/result.json, src/_tests/fixtures/44439/mutations.json, src/_tests/fixtures/44439/result.json, src/compute-pr-actions.ts
=> Use the access rights function to determine which project column to place the PR

PR-Trigger/index.js, src/execute-pr-actions.ts, src/side-effects/merge-codeowner-prs.ts
=> Add a concept of side-effects which allows for auto-merging the code-owners PR when it is green

src/comments.ts, src/compute-pr-actions.ts
* Use `info.stalenessInDays` which is the right number now.
* Increase the abandon warning time to about a week.
* Add a new `Staleness.PayAttention` which makes the stale count
displayed in the main comment.
=> Staleness work

src/compute-pr-actions.ts
Makes it easier to extend these parts later on
=> Minor code shuffle

src/pr-info.ts
`categorizeFile` uses one regexp to analize the path, and makes a
decision based on the suffix which should be easier to extend if needed,
including grabbing the subpath (e.g., to require `test` in the name of
test files).
Use a `Set` for `getPackagesTouched` just because I was waiting...
=> Random improvements in `pr-info.ts`

src/compute-pr-actions.ts
Still works the same, but will make the following changes easier to follow.
=> Refactor `hasFinalApproval` in a functional way

src/_tests/fixtures/44299-with-files/_downloads.json, src/_tests/fixtures/44299-with-files/_files.json, src/_tests/fixtures/44299-with-files/_response.json, src/_tests/fixtures/44299-with-files/derived.json, src/_tests/fixtures/44299-with-files/mutations.json, src/_tests/fixtures/44299-with-files/result.json, src/pr-info.ts, src/queries/recently-merged-prs-project.ts
Using 5 was wrong, especially since I'm adding a new one.
=> Fetch 100 columns in `GetRecentlyMergedPRsProjectQuery`

src/_tests/fixtures/44299-with-files/_downloads.json, src/_tests/fixtures/44299-with-files/_files.json, src/_tests/fixtures/44299-with-files/_response.json, src/_tests/fixtures/44299-with-files/derived.json, src/_tests/fixtures/44299-with-files/mutations.json, src/_tests/fixtures/44299-with-files/result.json, src/pr-info.ts, src/queries/recently-merged-prs-project.ts
Makes the result of local runs less confusing.
=> Print only the message when failing to parse owners

src/comments.ts, src/compute-pr-actions.ts, src/pr-info.ts
Keep a few that look like they might be useful in the future.
=> Remove some unused things, label a few that are kept

src/_tests/cachedQueries.json, src/commands/update-test-data.ts
* Add a comment to the cache file saying how to update it.
* Make it search up for the repo directory, since otherwise it would
sometimes produce the output in the wrong place.
=> Update cache and improve updating

src/_tests/fixtures/44402/mutations.json, src/_tests/fixtures/44402/result.json, src/compute-pr-actions.ts, src/scripts/daily.ts
Because it looks strange that there are no labels on these things.  Also
don't ignore them in `daily.ts`.
=> Add `Edits Infrastructure` for `no_packages` PRs

src/_tests/fixtures/43960-post-close/mutations.json, src/_tests/fixtures/43960-post-close/result.json, src/_tests/fixtures/44105/mutations.json, src/_tests/fixtures/44105/result.json, src/_tests/fixtures/44256/mutations.json, src/_tests/fixtures/44256/result.json, src/_tests/fixtures/44290/mutations.json, src/_tests/fixtures/44290/result.json, src/compute-pr-actions.ts, src/scripts/daily.ts
(Still show the `state.message` field for clearer logs.)
=> Move draft prs to `Needs Author Action`

PR-Trigger/index.js
And if another hook comes in for the same PR, then just do nothing, so
the later request will do everything.
Fixes #168
=> Delay replies by 30s

src/_tests/fixtures/38979/mutations.json, src/_tests/fixtures/38979/result.json, src/_tests/fixtures/44411/mutations.json, src/_tests/fixtures/44411/result.json, src/_tests/fixtures/44424-1-travis-instantly-finished/mutations.json, src/_tests/fixtures/44424-1-travis-instantly-finished/result.json, src/_tests/fixtures/44424-2-after-travis-second/mutations.json, src/_tests/fixtures/44424-2-after-travis-second/result.json, src/_tests/fixtures/46191/mutations.json, src/_tests/fixtures/46191/result.json, src/compute-pr-actions.ts
(Note that many tests list "couldn't fetch contents" as the reason,
since these tests were added before the contents was fetched and
checked.)
=> List reasons for meta files that are not meta-ok

src/pr-info.ts
Like #194, this change is to require only owner approval for certain edits that previously required maintainer approval.
The "required form" is taken from [dts-gen](https://github.com/microsoft/dts-gen/blob/af84657554e01fcfa81b210a43efd8236f476fd4/lib/definitely-typed.ts#L97-L117).
Owners can approve edits to the files list, as long as checks pass, so I removed `files` from both sides of the diff (so they're ignored). I moved the `isRelativePath()` check to microsoft/DefinitelyTyped-tools#127, to put it together with the other `checkFilesFromTsConfig()`/`OTHER_FILES.txt` checks.
`module`, `types`, `noEmit` and `forceConsistenCasingInFileNames` can only ever have a single, literal value, enforced by [dtslint](https://github.com/microsoft/dtslint/blob/952086da5617f3f2c94bc9aad849fe51732eb00e …
=> Make required form edits okay

src/pr-info.ts
Use a generic helper for this, and improve it by wrapping a try-catch
only around the needed parts that parse or compare user data.
=> Unify the repeated code that checks convergence to a required form

.github/workflows/daily.yml, .github/workflows/upload.yml, package.json
Should force contributors to have the minimum version, and allows us to deploy 👍🏻
=> Add engines to recommend node 12, and adds node12 to the upload yml

README.md
Nit. Without it I get
```Shell
> jest "44299"
No tests found, exiting with code 1
```
=> Add -- before npm test arguments

src/_tests/cachedQueries.json, src/util/cachedQueries.ts
Update the label cache, and sort it and the column names alphabetically
so future changes are more easily compared.
The changes in this commit is only in the labels:
* Added: "Unreviewed"
* Removed: "Formatting Revision Needed", "The Travis CI build failed",
"Author Approved", "Awaiting reviewer feedback".
=> Update cache, and make it stable

src/compute-pr-actions.ts, src/pr-info.ts, src/util/util.ts
Remove some unused code & imports, use a new `sameUser` utility to
compare usernames, fix a big.
=> Some minor leftover tweaks

src/_tests/cachedQueries.json
(Mop-up after the last PR, will merge immediately.)
=> Adjust `cachedQueries.json` to label renames

src/util/comment.ts
Trivial change, because there's a type for this so DRY?
=> Cosmetic: Reuse Comment type

src/pr-info.ts
This fixes the problem where an `UNKNOWN` value leads to the bot
toggling the conflicts label.  (See for example
DefinitelyTyped/DefinitelyTyped#48723.)
With this, it should be practical to make switch the daily run to once
every four hours (which I thought that I did a while ago).
=> Implement a retry mechanism for PR queries

src/compute-pr-actions.ts, src/pr-info.ts, src/urls.ts
https://github.com/DefinitelyTyped/dt-mergebot/pull/223#pullrequestreview-529504577
=> Link to explanation of the required form

.eslintrc.json, package.json
https://github.com/DefinitelyTyped/dt-mergebot/pull/252#pullrequestreview-546104748
=> Add ESLint

.github/workflows/test.yml
https://github.com/DefinitelyTyped/dt-mergebot/pull/252#pullrequestreview-546104748
=> Add ESLint to CI

src/_tests/fixtures/43695-duplicate-comment/_response.json, src/_tests/fixtures/43695-post-review/_response.json, src/_tests/fixtures/43695-post-review/mutations.json, src/_tests/fixtures/43695-post-review/result.json, src/_tests/fixtures/43695/_response.json, src/_tests/fixtures/43695/mutations.json, src/_tests/fixtures/43695/result.json, src/_tests/fixtures/43960-post-close/_response.json, src/_tests/fixtures/43960/_response.json, src/_tests/fixtures/43960/result.json, src/_tests/fixtures/44256/_response.json, src/_tests/fixtures/45836/_response.json, src/_tests/fixtures/45999/_response.json, src/_tests/fixtures/46120/_response.json, src/_tests/fixtures/48652-merge-offer/_response.json, src/_tests/fixtures/48652-prereq/_response.json, src/_tests/fixtures/48652-retract-merge-offer-and-prerequest/_response.json, src/_tests/fixtures/48652-retract-merge-offer-and-prerequest/mutations.json, src/_tests/fixtures/48652-retract-merge-offer-and-prerequest/result.json, src/_tests/fixtures/48652-retract-merge-offer/_response.json, src/_tests/fixtures/48652-retract-merge-offer/mutations.json, src/_tests/fixtures/48652-retract-merge-offer/result.json, src/_tests/fixtures/48708/_response.json, src/_tests/fixtures/48708/result.json, src/_tests/fixtures/48945/_response.json, src/_tests/fixtures/48945/result.json, src/comments.ts
=> Don't suggest dismissing reviewes

.eslintrc.json, list-project-columns.js, src/commands/process-single.ts, src/compute-pr-actions.ts, src/execute-pr-actions.ts, src/graphql-client.ts, src/pr-info.ts, src/run.ts
=> More linting

src/_tests/fixtures/44402/derived.json, src/_tests/fixtures/44402/mutations.json, src/_tests/fixtures/44402/result.json, src/compute-pr-actions.ts, src/pr-info.ts
Reopen https://github.com/DefinitelyTyped/dt-mergebot/pull/213#issuecomment-724204434
Apply the usual ("Maintainer Approved", "Other Approved") labels to PRs that don't affect packages.
=> Move no packages check after general labeling

src/_tests/fixtures/44402/mutations.json, src/_tests/fixtures/44402/result.json, src/_tests/fixtures/44989-14days/result.json, src/_tests/fixtures/44989-32days/result.json, src/_tests/fixtures/45627/result.json, src/_tests/fixtures/45884/result.json, src/_tests/fixtures/46008/result.json, src/compute-pr-actions.ts
=> Label and offer self merge together

src/pr-info.ts, src/urls.ts
Supersedes #223.
Co-authored-by: Jack Bates <jack@nottheoilrig.com>
=> Add link for `tslint.json` contents

src/_tests/fixtures/49841/derived.json, src/pr-info.ts, src/urls.ts
=> Link to tsconfig.json explanation

package-lock.json, src/schema/graphql-global-types.ts
Update `package-lock.json`, and a minor schema addition.
=> Updates following last change

package.json, src/graphql-client.ts, src/pr-info.ts, src/queries/SHA1-to-PR-query.ts, src/queries/all-open-prs-query.ts, src/queries/card-id-to-pr-query.ts, src/queries/file-query.ts, src/queries/label-columns-queries.ts, src/queries/pr-query.ts, src/queries/process-many-query.ts, src/queries/projectboard-cards.ts, src/queries/schema/GetAllOpenPRsAndCardIDs.ts, src/queries/schema/GetFileContent.ts, src/queries/schema/GetLabels.ts, src/queries/schema/GetProjectColumns.ts, src/queries/schema/PR.ts, src/queries/schema/ProcessManyPRs.ts, src/util/cachedQueries.ts
=> Upgrade Apollo Client

src/compute-pr-actions.ts
All uses are within `process`, so define it there.
=> No need to keep `headCommitAbbrOid` in the (extended) info

PR-Trigger/index.js
I'm seeing these crashes in the logs:
```
Result: Failure Exception: Worker was unable to load function PR-Trigger: 'Error: Cannot find module '@octokit/webhooks/verify'' Stack: Error: Cannot find module '@octokit/webhooks/verify' at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15) at Function.Module._load (internal/modules/cjs/loader.js:562:25) at Module.require (internal/modules/cjs/loader.js:692:17) at require (internal/modules/cjs/helpers.js:25:18) at Object.<anonymous> (/home/site/wwwroot/PR-Trigger/index.js:7:16) at Module._compile (internal/modules/cjs/loader.js:778:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10) at Module.load (internal/modules/cjs/loader.js:653:32) at tryModuleLoad (internal/modules/cjs/loader.js:593:12) at …
```
=> Use verify via the main webhook object

src/_tests/fixturedActions.test.ts, src/commands/create-fixture.ts
Also replace `lstatSync()` with `readdirSync()` `withFileTypes` option.
=> Cosmetic: use readJsonSync()

PR-Trigger/.gitignore, PR-Trigger/function.json, PR-Trigger/tsconfig.json
Imported from [this PR](https://github.com/elibarzilay/dt-mergebot/pull/2).
=> Keep output files in bin directory

.eslintrc.json, src/compute-pr-actions.ts, src/execute-pr-actions.ts, src/pr-info.ts, src/util/fetchFile.ts, tsconfig.json
Any objection to adding this rule? https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unnecessary-condition.md
=> Add no-unecessary-condition ESLint rule

src/queries/pr-query.ts
Hopefully that will get the relevant one.
Fixes #322 (see that for further details).
=> Try getting just one commit

.eslintrc.json, package-lock.json, package.json, src/pr-info.ts
Any objection to adding this rule? https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/prefer-array-some.md
=> Add prefer-array-some ESLint rule

src/_tests/fixtures/43960-post-close/derived.json, src/_tests/fixtures/44105/derived.json, src/_tests/fixtures/44256/derived.json, src/_tests/fixtures/44290/derived.json, src/_tests/fixtures/45982/derived.json, src/pr-info.ts
=> Remove pr_number from BotError and BotEnsureRemovedFromProject

src/compute-pr-actions.ts, src/execute-pr-actions.ts, src/util/comment.ts, src/util/util.ts
=> Remove some unused exports

src/pr-info.ts
=> Use some enum strings directly

src/queries/all-open-prs-query.ts, src/queries/schema/GetAllOpenPRsAndCardIDs.ts
Instead of fetching every cursor, just fetch `pageInfo.endCursor`. Also, `pageInfo.hasNextPage` saves one final network request.
=> Use pageInfo for pagination

.eslintrc.json, src/_tests/fixturedActions.test.ts, src/compute-pr-actions.ts, src/execute-pr-actions.ts, src/graphql-client.ts, src/pr-info.ts, src/pr-trigger.ts, src/queries/all-open-prs-query.ts, src/queries/projectboard-cards.ts, src/scripts/updateJSONFixtures.ts, src/util/fetchFile.ts
Add trailing commas to multiline objects. https://eslint.org/docs/rules/comma-dangle
=> Add comma-dangle ESLint rule

src/pr-trigger.ts
=> Extract debounce()

package-lock.json, package.json, src/pr-trigger.ts, src/side-effects/merge-codeowner-prs.ts
Use `eventHandler.on()`/`eventHandler.receive()`, which type checks both the event names and payloads. I opened separate PRs for #360, #361, and #362. Only the last commit belongs to this PR.
=> Type check webhook payloads

src/pr-trigger.ts
Mainly because I see log entries that have no indication of any work
done.
=> Add logging on `handleTrigger`

src/pr-trigger.ts
* Remove previous debugging logs
* Add useful logging: event+action names, GH & AZ ids
* Add debug output to figure out what causes bad PR numbers
=> Add proper logging

src/pr-trigger.ts
Makes it easier to look at the logs
=> Unify responses with log entries

src/pr-trigger.ts
Make `prFromCheckSuiteEvent` return a new ignore-this value when we
couldn't find a PR and there are `check_suite.pull_requests`.  From
looking at the logs, it seems to me that all of them are "reverse"
PRs (used by forks to pull updates from DT, mostly by a "pull bot").
Keep throwing an error if no PR was found and there are no such reverse
PRs.
=> Ignore nonexistent PR numbers

src/pr-trigger.ts
Considering switching from `check_suite` to `check_run` to get the name.
=> Debugging for `check_run`

src/compute-pr-actions.ts
Mainly: make `*REMOVE*` a part of `ColumnName`.  When it's used in a
staleness, it also makes the PR close before being removed.
=> Some simplifications

src/pr-info.ts, src/util/util.ts
Makes dealing with types simpler and the code shorter.
=> `findLast` -> `someLast`

src/_tests/fixtures/43160/mutations.json, src/_tests/fixtures/43160/result.json, src/_tests/fixtures/46191/mutations.json, src/_tests/fixtures/46191/result.json, src/_tests/fixtures/49841/mutations.json, src/_tests/fixtures/49841/result.json, src/_tests/fixtures/50429/mutations.json, src/_tests/fixtures/50429/result.json, src/comments.ts
Maybe it's not the most effective copy, but it does get the point across
=> Notes that we don't look at red builds

src/_tests/fixtures/43160/mutations.json, src/_tests/fixtures/43160/result.json, src/_tests/fixtures/43175/mutations.json, src/_tests/fixtures/43175/result.json, src/_tests/fixtures/44267/mutations.json, src/_tests/fixtures/44267/result.json, src/_tests/fixtures/45137/mutations.json, src/_tests/fixtures/45137/result.json, src/_tests/fixtures/45627/mutations.json, src/_tests/fixtures/45627/result.json, src/_tests/fixtures/45884/mutations.json, src/_tests/fixtures/45884/result.json, src/_tests/fixtures/45888/mutations.json, src/_tests/fixtures/45888/result.json, src/_tests/fixtures/46008/mutations.json, src/_tests/fixtures/46008/result.json, src/_tests/fixtures/46191/mutations.json, src/_tests/fixtures/46191/result.json, src/_tests/fixtures/46279/mutations.json, src/_tests/fixtures/46279/result.json, src/_tests/fixtures/46804/mutations.json, src/_tests/fixtures/46804/result.json, src/_tests/fixtures/51338/result.json, src/compute-pr-actions.ts
I'm not sure that this is enough to actually having it appear first, but
it doesn't hurt to try...
=> Ensure posting the welcome comment first

package-lock.json, src/pr-info.ts, src/pr-trigger.ts, src/queries/pr-query.ts
Fixing the build break which resulted from the recent
[`@types/node` change](https://github.com/DefinitelyTyped/dt-mergebot/pull/416).
Also, regenerate `package-lock.json` which started breaking `npm install`.
Also, clarification comment re `tooManyFiles`
=> Fix `setTimeout` types

src/run.ts
This ensures that a failure actually gets reported as a failure in the execution of the workflow on GitHub Actions
=> Add a proper handling of failures when executing the command

src/run.ts
#454 was merged with a linting error reported on it (or maybe not reported if the CI run was not approved before the merge)
=> Fix indentation to satisfy the linter

.github/workflows/upload.yml
The old way isn't working, let's try the way documented at https://learn.microsoft.com/en-us/azure/azure-functions/functions-how-to-github-actions?tabs=javascript
=> Update deploy credentials

.github/workflows/upload.yml
oh no, another reference to bin/ that needs to be dist/
=> Fix sanity listing

.github/workflows/upload.yml
Internal documentation says to do this in a couple of different places.
=> try webapps-deploy github action

.github/workflows/daily.yml
builds into dist/ not bin/ now
=> Fix daily.yml build location

src/pr-info.ts
Goes with https://github.com/microsoft/DefinitelyTyped-tools/pull/788. This file doesn't need any checks as CI validates it and messing with package versions seems like it should be self-service.
=> Ignore .npmignore changes; checked in CI

.github/workflows/test.yml, package-lock.json, package.json, src/_tests/fixturedActions.test.ts, src/commands/create-fixture.ts, src/functions/discussions-trigger.ts, src/graphql-client.ts, src/util/io.ts, src/util/util.ts, src/util/verify.ts
There's something else going wrong here; I can't make it break locally but I'm just going to pull this back for now.
=> Revert all dep upgrades

.github/workflows/deploy.yml, package-lock.json, package.json, src/compute-pr-actions.ts, src/functions/index.ts, src/run.ts, tsconfig.json
This will make it easier to move to pnpm (because symlinks can't go into zips and work on Azure Functions) and eventually move to dt-tools (which uses pnpm).
=> Bundle rather than uploading the entire repo

.github/workflows/deploy.yml
No zip command on Windows, it seems. Nothing here is platform specific.
=> Build for deploy on linux
