DefinitelyTyped/dt-mergebot

PR-Trigger/index.js
I'm not certain why we're not getting PR details - so this prints the query used to find the PR for a commit
=> Improve status fail logging

PR-Trigger/index.js
GitHub seems to send a `submitted` and `edited` request simultaneously when you submit a review 😐
=> Ignore PR review edits

PR-Trigger/index.js, src/compute-pr-actions.ts, src/queries/status-to-PR-query.ts
Travis validates that master is green, which sends status updates to the webhook - we don't need to do work there, so this doesn't raise when we don't need to do work
=> Handle NOOPing on status updates from merged PRs

src/_tests/fixtures/43136/result.json, src/_tests/fixtures/43144/mutations.json, src/_tests/fixtures/43144/result.json, src/_tests/fixtures/43151/result.json, src/_tests/fixtures/43160/result.json, src/_tests/fixtures/43175/result.json, src/_tests/fixtures/43235/result.json, src/_tests/fixtures/43314/result.json, src/_tests/fixtures/43695-duplicate-comment/result.json, src/_tests/fixtures/43695-post-review/result.json, src/_tests/fixtures/43695/result.json, src/_tests/fixtures/43960/result.json, src/_tests/fixtures/44267/result.json, src/_tests/fixtures/44282/result.json, src/_tests/fixtures/44288/result.json, src/_tests/fixtures/44299/result.json, src/_tests/fixtures/44316/result.json, src/_tests/fixtures/44343-pending-travis/result.json, src/_tests/fixtures/44343-pre-travis/result.json, src/_tests/fixtures/44343/result.json, src/_tests/fixtures/44411/result.json, src/_tests/fixtures/44424-1-travis-instantly-finished/result.json, src/_tests/fixtures/44424-2-after-travis-second/result.json, src/compute-pr-actions.ts
This means we'll be able to see which need a poke, and which have been handled post-merge
=> Adds a label for self-merging

PR-Trigger/index.js, src/queries/status-to-PR-query.ts
#95 would have worked... If the pull request was in the webhook, but oddly enough - it isn't. This brings back the sha->PR search query I removed.
=> Don't rely on the PR in the check suite webhook

src/queries/recently-merged-prs-project.ts
* Got some error from apollo when running locally (sometimes).
[This answer](https://stackoverflow.com/a/41981490/128595) suggests
having ids at all levels, and indeed adding them made it go away.
* Stringify `results.errors` since it's an array of json objects.
=> Fix two problems in `recently-merged-prs-project`

.gitignore
(`coverage` is for the generated jest coverage reports.)
=> `.gitignore`: fix and add `coverage`

src/_tests/fixtures/44989-40days/mutations.json, src/_tests/fixtures/44989-40days/result.json, src/compute-pr-actions.ts
Stale & bad PRs are abandoned as usual (= closed), but stale *good* PRs
are moved to the maintainer queue, to decide if they should be merged or
not.
=> Move all stale PRs to the maintainer queue

src/scripts/daily.ts
Makes it easier to see which PRs are ignored because they're draft PRs.
=> Show `remove` results in the output

src/_tests/fixtures/45836/_downloads.json, src/_tests/fixtures/45836/_owners.json, src/_tests/fixtures/45836/_response.json, src/_tests/fixtures/45836/derived.json, src/_tests/fixtures/45836/mutations.json, src/_tests/fixtures/45836/result.json, src/pr-info.ts
The code was already ignoring stale reviews for a different
`headRefOid`, but it might be that a second review approves a request
without changes, so the first review for the same author should be
ignored even if it's the same headref.
(Note that the test case still doesn't want to merge it, because the PR
also edited multiple packages.)
=> Consider only the last review from each author

src/_tests/fixtures/44299-with-files/_downloads.json, src/_tests/fixtures/44299-with-files/_files.json, src/_tests/fixtures/44299-with-files/_response.json, src/_tests/fixtures/44299-with-files/derived.json, src/_tests/fixtures/44299-with-files/mutations.json, src/_tests/fixtures/44299-with-files/result.json, src/pr-info.ts
Includes simple tests for valid `OTHER_FILES.txt` and `tslint.json`,
marking them as `package-meta-ok` which is ignored for the decision to
put a PR in the maintainer queue.
=> Add the ability to fetch meta files and test them

src/_tests/fixtures/43151/mutations.json, src/_tests/fixtures/43151/result.json, src/_tests/fixtures/43314/mutations.json, src/_tests/fixtures/43314/result.json, src/_tests/fixtures/43695-duplicate-comment/mutations.json, src/_tests/fixtures/43695-duplicate-comment/result.json, src/_tests/fixtures/44282/mutations.json, src/_tests/fixtures/44282/result.json, src/_tests/fixtures/44299-with-files/mutations.json, src/_tests/fixtures/44299-with-files/result.json, src/_tests/fixtures/44299/mutations.json, src/_tests/fixtures/44299/result.json, src/_tests/fixtures/44316/mutations.json, src/_tests/fixtures/44316/result.json, src/_tests/fixtures/45890/mutations.json, src/_tests/fixtures/45890/result.json, src/_tests/fixtures/45946/mutations.json, src/_tests/fixtures/45946/result.json, src/comments.ts, src/compute-pr-actions.ts, src/pr-info.ts
* If this is a single-owner package, and its popularity is `Popular`,
then make the required reviewers be "others" (and not "owners", which
doesn't apply for these packages).
* In the case of single-owner packages whose popularity is not
`Critical` (i.e., including the above case), spit out a comment
encouraging the owner to find someone else to review and maybe
recruit them as an owner.  (See my comment on #105.)
Closes #105.
=> Improve the situation for single owner packages

host.json
The `singleton` settings don't seem to have an effect, so try [this thing](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook-output) instead.
Note that this limits all interactions — if the bots becomes busy enough, it would be better to limit concurrency per PR instead, somehow.
=> (Try to) disable concurrent trigger runs

src/_tests/fixtures/43144/mutations.json, src/_tests/fixtures/43144/result.json, src/_tests/fixtures/44437/mutations.json, src/_tests/fixtures/44437/result.json, src/_tests/fixtures/44989-3days/mutations.json, src/_tests/fixtures/44989-3days/result.json, src/_tests/fixtures/44989-5days/mutations.json, src/_tests/fixtures/44989-5days/result.json, src/_tests/fixtures/44989-6days/mutations.json, src/_tests/fixtures/44989-6days/result.json, src/_tests/fixtures/45884/mutations.json, src/_tests/fixtures/45884/result.json, src/_tests/fixtures/45999/mutations.json, src/_tests/fixtures/45999/result.json, src/_tests/fixtures/46008/mutations.json, src/_tests/fixtures/46008/result.json, src/_tests/fixtures/46019/mutations.json, src/_tests/fixtures/46019/result.json, src/comments.ts, src/compute-pr-actions.ts, src/pr-info.ts
Add text to the comment telling owners that it can be done --- *except*
when there are too many owners, or when there are multiple packages.
(Owners can still do it if there are many, only multiple packages block
the whole thing.)
Closes #98.
Also remove an unused `const approvals` line.
=> Allow owners to do a "ready to merge" self-merge

src/_tests/fixtures/43960-post-close/derived.json, src/_tests/fixtures/43960-post-close/mutations.json, src/_tests/fixtures/43960-post-close/result.json, src/_tests/fixtures/44105/derived.json, src/_tests/fixtures/44105/mutations.json, src/_tests/fixtures/44105/result.json, src/_tests/fixtures/44256/derived.json, src/_tests/fixtures/44256/mutations.json, src/_tests/fixtures/44256/result.json, src/_tests/fixtures/44290/derived.json, src/compute-pr-actions.ts, src/pr-info.ts
My earlier commit moved all PRs with a `"remove"` info to NAA, but this
is wrong for PRs that are closed or merged.  So add an `isDraft` field
to the info, and move only the draft ones to NAA.
=> Fix handling of non-active PRs that are not draft

PR-Trigger/index.js
There were cases where the sha1 search didn't find a PR, probably
because the PR was already closed: avoid throwing an error and instead
show text in the log, which makes it easy to find these things
later (and will not mark the GH hook delivery as failed).
Note also the added `return`, which I think should have been there to
really be a NOOP.  (But maybe it *should have not been* a NOOP?)
=> Avoid throwing an error if we couldn't find a pr

src/_tests/fixtures/43960-post-close/mutations.json, src/_tests/fixtures/43960-post-close/result.json, src/_tests/fixtures/44105/mutations.json, src/_tests/fixtures/44105/result.json, src/_tests/fixtures/44256/result.json, src/compute-pr-actions.ts
Should have used `shouldRemoveFromActiveColumns` for these so they're
still removed from wherever they were.
=> Fix handling non-draft non-closed prs yet again

PR-Trigger/index.js, host.json, src/pr-info.ts
Trying to debug why there is no `pullRequest` data in some cases.  Also,
disable sequential http processing to see if that causes the
weirdnesses.
=> Temporary: Show failed data, disable sequential processing

src/_tests/fixtures/46279/_downloads.json, src/_tests/fixtures/46279/_files.json, src/_tests/fixtures/46279/_response.json, src/_tests/fixtures/46279/derived.json, src/_tests/fixtures/46279/mutations.json, src/_tests/fixtures/46279/result.json, src/compute-pr-actions.ts
Make the main checklist show
> Most recent commit is approved by type definition owners or DT maintainers
It still is confusing that it's only a minor phrasing response for
blessing the PR, but it's still in the maintainer queue column.  It
might be better to have something more concrete for single owners, but
anything I can think about is a major change.
=> Slight improvement for single owners

src/compute-pr-actions.ts
I don't think that it should make a difference since the default label
value is `false`, but maybe some mid-function failure made it sometimes
baheve as it did on DefinitelyTyped/DefinitelyTyped#44857.
=> Set author-attention labels with the rest

src/_tests/fixtures/45836/mutations.json, src/_tests/fixtures/45836/result.json, src/compute-pr-actions.ts, src/pr-info.ts
This attacks two problems:
- You edit a dependency, then you have to update downstream tests as well as your own
-  You see a non-sensical error message when blocked by being on multiple packages: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46321
Will commenting inline
=> A quick stab at improving the state of editing multiple packages

src/pr-info.ts
Should be less easy to miss, but still cover the case of a pr with tests
in a different package.
=> Count packages with non-test files, instead of with definitions

src/queries/SHA1-to-PR-query.ts, src/queries/card-id-to-pr-query.ts, src/queries/schema/CardIdToPr.ts, src/scripts/daily.ts
When doing the daily scan, close cards of closed PRs.
Note that the bot could respond to a close event and remove the card
then, but there are very few of these anyway.  (This would require
changing `PR-Trigger/index.js` and the rest of the code.)
=> Delete cards of closed PRs

src/_tests/fixtures/43151/mutations.json, src/_tests/fixtures/43151/result.json, src/_tests/fixtures/43314/mutations.json, src/_tests/fixtures/43314/result.json, src/_tests/fixtures/43695-duplicate-comment/mutations.json, src/_tests/fixtures/43695-duplicate-comment/result.json, src/_tests/fixtures/44299-with-files/mutations.json, src/_tests/fixtures/44299-with-files/result.json, src/_tests/fixtures/44299/mutations.json, src/_tests/fixtures/44299/result.json, src/_tests/fixtures/44316/mutations.json, src/_tests/fixtures/44316/result.json, src/_tests/fixtures/44439/mutations.json, src/_tests/fixtures/44439/result.json, src/_tests/fixtures/45890/mutations.json, src/_tests/fixtures/45890/result.json, src/_tests/fixtures/45946/mutations.json, src/_tests/fixtures/45946/result.json, src/_tests/fixtures/46279/mutations.json, src/_tests/fixtures/46279/result.json, src/_tests/fixtures/46879/mutations.json, src/_tests/fixtures/46879/result.json, src/compute-pr-actions.ts
This finally makes the NMA column more useful as an indicator of when a
PR cannot be blessed away.
* Sorted out `otherOwners` and related:
- made it into a function
- new `noOtherOwners` function
(Not efficient but hukaires.)
* Rename `hasFinalApproval` -> `getApproval`, and make it also return a
`blessable` boolean, which is how the above is implemented.
=> Move PRs to NMA when the cannot be blessed

src/pr-info.ts
Fixes the state in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47629 where the missing head commit shows as an error, but that's not even relevant on a closed PR 👍🏻
=> Check that the PR is open before gettng the head commit

src/pr-info.ts
I moved this check to microsoft/DefinitelyTyped-tools#127, to put it together with the other `checkFilesFromTsConfig()`/`OTHER_FILES.txt` checks.
=> Move isRelativePath() to @definitelytyped/definitions-parser

PR-Trigger/index.js, src/_tests/fixtures/45946/mutations.json, src/_tests/fixtures/45946/result.json, src/compute-pr-actions.ts
* Combine the `process.version` output into the HTTP message, to reduce
log lines.
* Get rid of `dangerLevel` values:
- `Infrastructure`: replaced earlier by `editsInfra`
- `MultiplePackagesEdited`: replaced by `hasMultiplePackages`
- `ScopedAndConfiguration`: replaced by `editsConfig`
(This leads to a minor test change, showing the `Config Edit` label
together with `Edits Infrastructure`; the previous single
`dangerLevel` value meant that it could not show both.)
- `ScopedAndTested`: replaced by `hasTests`, and `requireMaintainer`
that replaces `!== "ScopedAndTested"`
- `ScopedAndUntested`: all actual uses replaced by `!hasTests`
* Split `getApproval` into `getApproverKind` + `getApproval`.
=> More refactoring work

src/_tests/fixturedActions.test.ts, src/commands/create-fixture.ts, src/pr-info.ts, src/util/npm.ts
Actually, use the month up to a week before `lastPushDate`, in case it
takes npm some time to update the numbers.
This should make the download numbers stable, avoiding the wobble seen
in DefinitelyTyped/DefinitelyTyped#46778.
Fixes #209.
=> Get monthly download count for the month up to the `lastPushDate`

src/pr-info.ts
Just a thought, generalizing the ignored keys seems like a good fit for JSON Patch, especially since we're already using it, for `makeJsonCheckerFromCore()` no less.
Doesn't make a functional difference, just cute :smiley_cat:
=> Reuse JSON Patch to ignore keys

src/execute-pr-actions.ts, src/util/comment.ts
Trivial and doesn't make a functional difference. Makes `parse()` and `make()` more symmetrical.
=> Pass Comment whole

package-lock.json, package.json, src/compute-pr-actions.ts, src/run.ts
Two commits:
* Reorganize values to make a bit more sense.
* Add and edit some values (description, edit urls to the actual repo).
* Not that it used, but bump the version.
* Update `package-lock.json`.
* Move `@types/jest` into `devDependencies`.
There's a bunch of stuff in `commands` and `scripts`, but it's a mess to
update all of them.  Instead, this is a single `run` script that can be
used as a drop-in replacement for `daily`, which can do a dry run, show
various info (including the new `ExtendedPrInfo`) in multiple formats,
and can also operate on a selection of PRs.
=> Run script

src/_tests/fixturedActions.test.ts, src/_tests/fixtures/45982/derived.json, src/commands/create-fixture.ts, src/pr-info.ts
To avoid `RangeError: Invalid time value` when testing changes that make an existing fixture no longer error. RangeError is due to `getNow()` calling `new Date(readJSON(derivedPath).now)`, and `now` being `undefined` in `derived.json`.
=> Add "now" to bot error fixtures

src/compute-pr-actions.ts, src/execute-pr-actions.ts, src/pr-info.ts, src/util/cachedQueries.ts, src/util/util.ts
https://github.com/DefinitelyTyped/dt-mergebot/pull/235#discussion_r532957271
How about `noNullish()`? [`NonNullable<Type>`](https://www.typescriptlang.org/docs/handbook/utility-types.html#nonnullabletype) is somewhat analogous but "nullable" doesn't describe values. I went with "nullish" like ["nullish coalescing"](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#nullish-coalescing), "nullish checks", etc.
=> Rename noNulls() -> noNullish()

src/_tests/fixturedActions.test.ts, src/_tests/fixtures/43960-post-close/derived.json, src/_tests/fixtures/44105/derived.json, src/_tests/fixtures/44256/derived.json, src/_tests/fixtures/44290/derived.json, src/commands/create-fixture.ts, src/compute-pr-actions.ts, src/pr-info.ts
- Name `PrInfo | BotEnsureRemovedFromProject | BotNoPackages | BotError` to reduce repetition
- Fix `Property 'now' does not exist on type ...` now that it's not `any`
=> Apply input type to JSON output to check safety

src/_tests/fixtures/44402/mutations.json, src/_tests/fixtures/44402/result.json, src/compute-pr-actions.ts
* New `hasEditedPackages`: which is true when there *are* packages that
are not new.  (I.e., not counting infra changes.)
* Use that as a condition for `No Other Owners`, so it doesn't turn on
for infra PRs.
* Do the same for `Config Edit`, though there are no tests affected.
Supersedes #267.
=> Drop `No Other Owners` on infra PRs

.eslintrc.json, package-lock.json, package.json, src/compute-pr-actions.ts, src/execute-pr-actions.ts, src/pr-info.ts, src/util/util.ts
This is a pedantic change, so please dismiss it if it's unwelcome.
I'd like to prefer `.find()` over `.filter()[0]`, and I'd like to use tools to spot cases of it. So what I did was first add ESLint with a relaxed configuration, then added this [prefer-array-find](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/prefer-array-find.md) rule.
=> Prefer .find() over .filter()[0]

src/compute-pr-actions.ts
This is a cosmetic change, please dismiss it if it's unwelcome. We can just call `urls.review()` as needed?
=> Remove reviewLink from ExtendedPrInfo

src/pr-info.ts
Previously, I changed it to re-run the query if `mergeable` is `UNKNOWN`
because it sometimes takes a few seconds for the GH api to update this
information.  Turns out that this should be done *only* for PRs that are
`OPEN`, in other states (`CLOSED` & `MERGED`) it's *expected* to be
`UNKNOWN`.  This broke the removal of project cards for closed/merged
PRs, since it would just spin the 5 retries while getting `UNKNOWN`
every time, eventually treating it as bogus (and also timing out the
gateway).
Should fix #278.
=> Fix re-running of queries in pr-info

src/pr-info.ts
Like commit c525f36 (Move isRelativePath() to
@definitelytyped/definitions-parser, 2020-10-16), I moved this check to
microsoft/DefinitelyTyped-tools#136, to put it together with the other
OTHER_FILES.txt checks.
=> Move empty OTHER_FILES.txt check to @definitelytyped/definitions-parser

package.json, src/execute-pr-actions.ts, src/graphql-client.ts, src/run.ts, src/side-effects/merge-codeowner-prs.ts
We already depend on `@octokit/graphql-schema` which ships types for these inputs. Use them to catch errors at build time.
=> Type check mutation inputs

src/_tests/fixtures/43136/_response.json, src/_tests/fixtures/43136/derived.json, src/_tests/fixtures/43144/_response.json, src/_tests/fixtures/43151/derived.json, src/_tests/fixtures/43160/_response.json, src/_tests/fixtures/43175/_response.json, src/_tests/fixtures/43695/_response.json, src/_tests/fixtures/44282/derived.json, src/_tests/fixtures/44290/_response.json, src/pr-info.ts, src/queries/pr-query.ts, src/queries/schema/PR.ts, src/util/util.ts
`pullRequest.comments` and `pullRequest.timelineItems(itemTypes: ISSUE_COMMENT)` are the same thing, so use one or the other. Trims the query without changing the behavior.
=> Don't query comments twice

src/pr-info.ts, src/queries/SHA1-to-PR-query.ts, src/queries/all-open-prs-query.ts, src/queries/card-id-to-pr-query.ts, src/queries/file-query.ts, src/queries/label-columns-queries.ts, src/queries/pr-query.ts, src/queries/projectboard-cards.ts, src/util/cachedQueries.ts, src/util/fetchFile.ts
Instead of passing them independently at the call site (`query<T, TVariables>()`) https://github.com/apollographql/apollo-client/blob/main/CHANGELOG.md#user-content-improvements-9:~:text=allows%20the%20APIs%20to%20infer%20the,types%20explicitly%20at%20the%20call%20site
As a result of binding types to queries, this PR type checks variables in a couple places that were missed before. ~This PR is a draft because it depends on #301.~ Ready now :+1:
=> Bind data and variable types to queries

src/_tests/fixturedActions.test.ts, src/commands/create-fixture.ts, src/execute-pr-actions.ts, src/graphql-client.ts, src/run.ts
Cosmetic suggestion, please dismiss if it's not an improvement.
Replace `asJson()` with `toJSON()`, which `JSON.stringify()` calls automatically.
=> asJson() -> toJSON()

src/commands/create-fixture.ts
Because `create-fixture.ts` and [`fixturedActions.test.ts`](https://github.com/DefinitelyTyped/dt-mergebot/blob/756610c890cbb5b381fa2a1ad501ba418da48f07/src/_tests/fixturedActions.test.ts#L33) process different responses (unscrubbed and scrubbed) they can have different outputs, e.g. different mutations. The differences cause freshly created fixtures to fail, requiring a subsequent `--updateSnapshot`.
This change makes `create-fixture.ts` process the same (scrubbed) response as `fixturedActions.test.ts`, resulting in the same outputs and the fixture passing.
=> Process scrubbed response so created fixtures pass

.gitignore, PR-Trigger/index.js, PR-Trigger/tsconfig.json, package.json, src/tsconfig.json, tsconfig.json
Related to #294, but also as a step towards switching
`PR-Trigger/index.js` to TS so we can avoid more silly problems as after
the recent library updates.
Note that `PR-Trigger/tsconfig.json` is a bit bogus now:
* It creates its output in `bin/PR-Trigger`, but that output is not
used (and wouldn't work because it needs to be with the rest of the
azure function stuffs) -- I'd disable generating it if it was
possible.
* In the future, it should switch to an `index.ts`, which would make it
possible to use its own directory for the js file.
=> Switch to project references

src/_tests/fixturedActions.test.ts, src/commands/create-fixture.ts, src/compute-pr-actions.ts, src/execute-pr-actions.ts, src/pr-info.ts, src/pr-trigger.ts, src/run.ts
What do you think about factoring `BotFail` out of `BotResult`?
Instead of checking for `!prInfo` in `deriveStateForPR()` and also checking `state.type === "fail"` immediately afterwards (to narrow `BotResult` -> `BotNotFail`), replace the second check (`state.type === "fail"`) with `!prInfo`, move it ahead of `deriveStateForPR()` and call `deriveStateForPR()` on the non-null `prInfo`?
Also, instead of passing the whole GraphQL result to `executePrActions()` and then non-null asserting `info.repository!.pullRequest!`, just pass the non-null pull request data, like `deriveStateForPR()`.
No change in behavior, just cleave `BotFail` from `BotNotFail` and handle them separately, before and after `deriveStateForPR()`. Also makes the `executePrActions()` signature (slightly) stricter.
=> Check for failure before deriveStateForPR() vs. after

src/_tests/fixtures/44989-14days/mutations.json, src/_tests/fixtures/44989-14days/result.json, src/_tests/fixtures/48708/mutations.json, src/_tests/fixtures/48708/result.json, src/comments.ts, src/compute-pr-actions.ts
What do you think about including an absolute date? Viewing a PR I found it was a little hard to tell how much time was remaining. This change removes any doubt whether "in three weeks" means from when the comment was posted, and I imagine there are rare cases where the timer has already started by then, e.g. when the bot/timelines are edited.
=> Add absolute date to timeline comments

.eslintrc.json, src/_tests/fixturedActions.test.ts, src/commands/create-fixture.ts, src/commands/update-all-fixtures.ts, src/commands/update-test-data.ts, src/compute-pr-actions.ts, src/execute-pr-actions.ts, src/graphql-client.ts, src/pr-info.ts, src/pr-trigger.ts, src/queries/SHA1-to-PR-query.ts, src/queries/all-open-prs-query.ts, src/queries/card-id-to-pr-query.ts, src/run.ts, src/scripts/updateJSONFixtures.ts, src/util/CIResult.ts, src/util/cachedQueries.ts, src/util/comment.ts, src/util/fetchFile.ts, src/util/util.ts
* Indentation, semicolons, quotes, etc.
* Eslint rules to check these (ignoring some things that I couldn't
figure out a way to sensible-ize).
* Drop the `CIResult` enum and use the strings directly instead.
=> More cleanups

src/compute-pr-actions.ts, src/util/util.ts
- Day.js/Moment.js `.diff()` already truncates the result (since Moment.js 2.0.0), no need for `Math.floor()`
- `.diff()` accepts a `Date`
=> Call Day.js directly

src/_tests/fixturedActions.test.ts, src/_tests/fixtures/43960-post-close/derived.json, src/_tests/fixtures/44105/derived.json, src/_tests/fixtures/44256/derived.json, src/_tests/fixtures/44290/derived.json, src/commands/create-fixture.ts, src/compute-pr-actions.ts, src/pr-info.ts
Slightly stricter than `string`. Consistent with the rest of `PrInfo` (`lastPushDate`, `lastActivityDate`, etc.).
Also, use Day.js for `tooEarlyForLabelsOrProjects`.
Cosmetic changes, no change in behavior.
=> Make now a Date

package.json
We don't need types at runtime? Minor cleanup.
=> Move some dependencies -> devDependencies

src/pr-info.ts, src/queries/SHA1-to-PR-query.ts, src/queries/all-open-prs-query.ts, src/queries/card-id-to-pr-query.ts, src/queries/projectboard-cards.ts
If we're never going to consult the cache (`fetchPolicy: "network-only"`) then don't waste memory storing results (`fetchPolicy: "no-cache"`)?
I don't expect this is a lot of memory -- I expect the number of objects is on the order of the number of active PRs? IDs should keep us from storing multiple copies. On the other hand the serverless function can run for long periods?
=> Replace fetch policy network-only -> no-cache

src/_tests/fixtures/44343-pending-travis/mutations.json, src/_tests/fixtures/44343-pending-travis/result.json, src/_tests/fixtures/44343-pre-travis/mutations.json, src/_tests/fixtures/44343-pre-travis/result.json, src/compute-pr-actions.ts
Instead of waiting unconditionally for one minute after the last push, only wait if the CI result is actually "missing".
=> Only delay if actually waiting for CI

src/pr-trigger.ts
`verify(req.body, sign(req.body))` is true by definition. Verify the actual signature instead.
=> Verify webhook signatures

src/_tests/fixtures/44989-14days/mutations.json, src/_tests/fixtures/44989-14days/result.json, src/_tests/fixtures/48708/mutations.json, src/_tests/fixtures/48708/result.json, src/compute-pr-actions.ts
The timelines expire on (`since` + the maximum staleness), not (`now` + the maximum staleness). I introduced this bug in #289, mea culpa!
=> Fix timeline expires math

src/pr-trigger.ts
Try to figure out why every once in a while there is a failure to get
the PR number from a `check_suite` event.
=> Debug output

src/pr-trigger.ts
See the comment: it's often empty, and when it's not, it's with related
PRs in *other* repos.
Leaving some logging for a bit more, to find out what are these PRs.
=> Give up on using `event.payload.check_suite.pull_requests`

src/pr-info.ts
So there are no suspicious flags raised when using `dom` too.
=> Ignore case of entries in `compilerOptions.lib`

src/commands/create-fixture.ts, src/pr-info.ts, src/pr-trigger.ts, src/queries/all-open-prs-query.ts, src/queries/pr-query.ts, src/queries/schema/PR.ts, src/queries/schema/PRFiles.ts, src/run.ts
This reduces maintainer load since there are less suspicious PRs, and
make it easier to see if the PR is well behaved.
Move the whole retry + fetch rest thing into `src/queries/pr-query`.
Leave the `tooManyFiles` bits in for now, but if this is stable enough
they should eventually be removed.
=> Fetch *all* files

src/compute-pr-actions.ts
Self-merge requires the bot offering the merge, first, and if that
wasn't done, avoid proceeding with the unreviewed timeline.
=> Minor bugfix

src/pr-info.ts
* Show a list of keys to check when a file is suspect (except for
all-numeric paths, when checking `OTHER_FILES.txt`).
* Ignore `compilerOptions.jsx`, as specified in the DT README.
=> Improve config checker

Playground-Info/function.json, Playground-Info/index.mjs
Adds a new API end-point which allows anyone to grab the bot's opinion on an arbitrary PR number. You should rightly be wondering what the goal is, well I'm exploring a playground for reviewing DT PRs and I need data from GitHub - specifically a bunch of PR metadata.
To get useful metadata _reliably_ you need an access token etc, so I thought about re-using an existing API - then I wondered, well, I have to re-create _some_ of the logic from the state from the bot. Why not just have the bot fix both issues? So, now you can make an API call to get the PR state for an arbitrary PR.
=> Adds a new webhook which returns the JSON data for a PR

src/pr-trigger.ts
`verify()` from octokit changed to [require a string
input](https://github.com/octokit/webhooks-methods.js/pull/21) in v2.
=> Fix brokenness in `verify()`

src/_tests/cachedQueries.json, src/_tests/fixtures/44424-1-travis-instantly-finished/mutations.json, src/_tests/fixtures/44424-1-travis-instantly-finished/result.json, src/_tests/fixtures/44424-2-after-travis-second/mutations.json, src/_tests/fixtures/44424-2-after-travis-second/result.json, src/basic.ts, src/compute-pr-actions.ts, src/pr-info.ts, src/queries/pr-query.ts, src/run.ts
This should avoid [the problem seen in this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62106) ***BUT*** it means that when there are too many files, it should be taken more seriously, since the bot wouldn't go over any of the extra ones.
So I also added a "Too Many Files" label and made it use it (otherwise it would only show an easy-to-miss line at the bottom of the welcome message).
Fixes #447. Probably. Maybe.
=> If there are over 500 files changed, don't fetch more than that

src/pr-info.ts
This checks every line in a comment for the phrase "ready to merge" in the beginning, rather than just looking at the start of the whole comment.
=> check merge trigger phrase at the start of every line

.github/workflows/daily.yml
The dispatch will be done from a scheduled workflow running in the main DT repository because scheduled workflows deactivate themselves automatically when the repo has not recent activity.
Refs #452
=> Change the daily workflow to be dispatched manually

src/pr-info.ts
This will avoid the error happening in https://github.com/DefinitelyTyped/dt-mergebot/actions/runs/3787571682/jobs/6439491663#step:6:133 when processing https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62421/files#diff-34d1b361cc4bb2acbb26b336268966889fd039de3e398c8f2b70ae24e27a9101
=> Fix the validation of PRs with a tsconfig.json not configuring lib

.github/workflows/daily.yml, .github/workflows/test.yml, .github/workflows/upload.yml
This avoids using the deprecated node 12.x runtime.
=> Update github actions to their latest version

src/pr-info.ts
...so we can start migrating to `node16`. Once everything is migrated, we can put this back, enforcing `node16`.
=> Do not enforce compilerOptions `module`

host.json
Which matches the Functions runtime 4, and somehow, probably, version 2 of Microsoft.Azure.Functions.ExtensionBundle
=> Upgrade to @azure/functions@3

src/functions/api.ts, src/run.ts
dtmergebot's API used to have CORS enabled. v2 broke [orta/playground-dt-review](https://github.com/orta/playground-dt-review/pull/6)
Considering that the plugin is still shown in comments on the dt repo, it'd be better to enable CORS. Currently that "You can test the changes of this PR in the Playground." thing doesn't work.
If abuse is a concern, we can limit it to just `typescriptlang.org`
=> fix: enable cors for api routes

.github/workflows/daily.yml
Rather than using a token to trigger this from the DT repo, just do the schedule here, then use a nifty action to keep the workflow from being disabled.
=> Move daily schedule to this repo, keepalive

package-lock.json, package.json
Not sure why but the newer version of functions doesn't register any of the endpoints. Rolling that back for now.
=> Downgrade functions back to 4.0.0-alpha.10

.github/workflows/test.yml, package-lock.json, package.json, src/_tests/fixturedActions.test.ts, src/commands/create-fixture.ts, src/functions/discussions-trigger.ts, src/graphql-client.ts, src/util/io.ts, src/util/util.ts, src/util/verify.ts
The main problem was that `@octokit/webhooks-methods` was not marked as a prod dep, so during deployment was being pruned.
=> Re-up deps
